# SolverForge — delta hackerman theme
# Generated by solverforge-theme-apply — do not edit manually

[delta]
    syntax-theme = ansi
    minus-style = "{{ color1 }}"
    minus-emph-style = "bold {{ color1 }}"
    plus-style = "{{ color2 }}"
    plus-emph-style = "bold {{ color2 }}"
    hunk-header-style = "{{ color5 }}"
    hunk-header-decoration-style = "{{ color8 }} ul"
    file-style = "bold {{ accent }}"
    file-decoration-style = "{{ accent }} ul"
    line-numbers-minus-style = "{{ color1 }}"
    line-numbers-plus-style = "{{ color2 }}"
    line-numbers-left-style = "{{ color8 }}"
    line-numbers-right-style = "{{ color8 }}"
