# SolverForge — eza hackerman theme (sourced as env vars)
# Generated by solverforge-theme-apply — do not edit manually

export EZA_COLORS="da={{ color5_strip }}:di={{ accent_strip }}:fi={{ foreground_strip }}:ln={{ color6_strip }}:ex={{ color1_strip }}:ur={{ color2_strip }}:uw={{ color3_strip }}:ux={{ color1_strip }}:ue={{ color1_strip }}:gr={{ color2_strip }}:gw={{ color3_strip }}:gx={{ color1_strip }}:tr={{ color2_strip }}:tw={{ color3_strip }}:tx={{ color1_strip }}:su={{ color5_strip }}:sf={{ color5_strip }}:xa={{ color8_strip }}:sn={{ color4_strip }}:sb={{ color4_strip }}:uu={{ accent_strip }}:un={{ color8_strip }}:gu={{ accent_strip }}:gn={{ color8_strip }}"
