# SolverForge — fzf hackerman theme (sourced as env vars)
# Generated by solverforge-theme-apply — do not edit manually

export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
  --color=bg+:{{ background }},bg:{{ background }},spinner:{{ accent }},hl:{{ color6 }} \
  --color=fg:{{ color8 }},header:{{ color6 }},info:{{ color5 }},pointer:{{ accent }} \
  --color=marker:{{ accent }},fg+:{{ foreground }},prompt:{{ accent }},hl+:{{ color6 }}"
