# SolverForge — lazygit hackerman theme
# Generated by solverforge-theme-apply — do not edit manually

gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "{{ accent }}"
      - bold
    inactiveBorderColor:
      - "{{ color8 }}"
    optionsTextColor:
      - "{{ color6 }}"
    selectedLineBgColor:
      - "{{ color0 }}"
    cherryPickedCommitBgColor:
      - "{{ color4 }}"
    cherryPickedCommitFgColor:
      - "{{ foreground }}"
    unstagedChangesColor:
      - "{{ color1 }}"
    defaultFgColor:
      - "{{ foreground }}"
    searchingActiveBorderColor:
      - "{{ color3 }}"
