# SolverForge — Sway border colors (hackerman theme)
# Generated by solverforge-theme-apply — do not edit manually

# class                 border          background      text            indicator       child_border
client.focused          {{ accent }}    {{ background }} {{ foreground }} {{ color6 }}   {{ accent }}
client.focused_inactive {{ color8 }}    {{ background }} {{ color8 }}    {{ color8 }}    {{ color8 }}
client.unfocused        {{ color0 }}    {{ background }} {{ color8 }}    {{ color0 }}    {{ color0 }}
client.urgent           {{ color1 }}    {{ background }} {{ foreground }} {{ color1 }}    {{ color1 }}
