# SolverForge — swaylock hackerman theme
# Generated by solverforge-theme-apply — do not edit manually

color={{ background_strip }}
inside-color={{ background_strip }}
inside-clear-color={{ background_strip }}
inside-ver-color={{ background_strip }}
inside-wrong-color={{ background_strip }}
key-hl-color={{ accent_strip }}
bs-hl-color={{ color1_strip }}
ring-color={{ color8_strip }}
ring-clear-color={{ color6_strip }}
ring-ver-color={{ color5_strip }}
ring-wrong-color={{ color1_strip }}
line-color=00000000
line-clear-color=00000000
line-ver-color=00000000
line-wrong-color=00000000
text-color={{ foreground_strip }}
text-clear-color={{ foreground_strip }}
text-ver-color={{ foreground_strip }}
text-wrong-color={{ foreground_strip }}
separator-color=00000000
indicator-radius=100
indicator-thickness=7
