/* SolverForge — swaync hackerman theme */
/* Generated by solverforge-theme-apply — do not edit manually */

* {
  font-family: "Fira Code", "FiraCode Nerd Font", monospace;
  font-size: 13px;
}

.notification-row {
  outline: none;
}

.notification {
  border-radius: 3px;
  margin: 4px 8px;
  padding: 0;
  border: 1px solid {{ accent }};
  background: {{ background }};
  color: {{ foreground }};
}

.notification-content {
  padding: 8px;
}

.close-button {
  background: {{ color8 }};
  color: {{ foreground }};
  border-radius: 3px;
  padding: 2px 6px;
  margin: 4px;
}

.close-button:hover {
  background: {{ accent }};
  color: {{ background }};
}

.notification-default-action,
.notification-action {
  border-radius: 3px;
  border: 1px solid {{ color8 }};
  background: {{ background }};
  color: {{ foreground }};
  padding: 4px;
  margin: 2px;
}

.notification-default-action:hover,
.notification-action:hover {
  background: {{ accent }};
  color: {{ background }};
}

.notification-group-headers {
  color: {{ accent }};
  font-weight: bold;
}

.control-center {
  background: {{ background }};
  border: 2px solid {{ accent }};
  border-radius: 3px;
  padding: 8px;
}

.control-center .notification {
  border: 1px solid {{ color8 }};
}

.widget-title {
  color: {{ accent }};
  font-weight: bold;
  margin: 4px 0;
}

.widget-title > button {
  background: {{ color8 }};
  color: {{ foreground }};
  border-radius: 3px;
  padding: 2px 8px;
}

.widget-title > button:hover {
  background: {{ accent }};
  color: {{ background }};
}
