/* SolverForge — per-app GTK overlay for the file manager.
   Generated by solverforge-theme-apply — do not edit manually.

   Loaded only through GTK_THEME for the file manager process; the session-wide
   GTK theme (Adwaita-dark, set by the desktop's own exec_always gsettings) is
   untouched. Adwaita-dark supplies the layout, metrics and widget behaviour —
   this file repaints the surfaces it hardcodes with the SolverForge palette.
   Adwaita's widget rules carry literal hex values, so the palette has to be
   applied as selectors here rather than as @define-color overrides. */

@import url("resource:///org/gtk/libgtk/theme/Adwaita/gtk-contained-dark.css");

/* ── surfaces ───────────────────────────────────────────────────────────── */
window, .background {
  background-color: {{ background }};
  color: {{ foreground }};
}

headerbar, .titlebar,
headerbar:backdrop, .titlebar:backdrop {
  background-color: {{ background }};
  color: {{ foreground }};
  border-color: {{ color8 }};
  box-shadow: none;
}

headerbar .title, .titlebar .title { color: {{ foreground }}; }
headerbar .subtitle { color: {{ color8 }}; }
headerbar:backdrop .title, headerbar:backdrop .subtitle { color: {{ color8 }}; }

/* ── content views: file list, icon grid, sidebar tree ──────────────────── */
.view, iconview,
.view text, iconview text, textview text,
treeview.view, treeview.view header button {
  background-color: {{ background }};
  color: {{ foreground }};
}

.view:backdrop, iconview:backdrop,
.view text:backdrop, textview text:backdrop,
treeview.view:backdrop {
  background-color: {{ background }};
  color: {{ color8 }};
}

.view:disabled, iconview:disabled, textview text:disabled {
  background-color: {{ background }};
  color: {{ color8 }};
}

.view:hover, iconview:hover, treeview.view:hover { background-color: {{ color0 }}; }

/* ── selection ──────────────────────────────────────────────────────────── */
.view:selected, iconview:selected,
.view text:selected, textview text:selected,
treeview.view:selected,
.view:selected:focus, iconview:selected:focus, treeview.view:selected:focus {
  background-color: {{ accent }};
  color: {{ background }};
}

.view:selected:backdrop, iconview:selected:backdrop,
treeview.view:selected:backdrop {
  background-color: {{ color8 }};
  color: {{ background }};
}

/* ── sidebar / places ───────────────────────────────────────────────────── */
.sidebar, stacksidebar, placessidebar,
.sidebar list, placessidebar list {
  background-color: {{ background }};
  color: {{ foreground }};
}

.sidebar list row, placessidebar list row { color: {{ foreground }}; }
.sidebar list row:hover, placessidebar list row:hover { background-color: {{ color0 }}; }
.sidebar list row:selected, placessidebar list row:selected {
  background-color: {{ accent }};
  color: {{ background }};
}
.sidebar list row:selected:backdrop, placessidebar list row:selected:backdrop {
  background-color: {{ color8 }};
  color: {{ background }};
}

/* ── buttons ────────────────────────────────────────────────────────────── */
button, button.flat {
  background-color: {{ color0 }};
  color: {{ foreground }};
  border-color: {{ color8 }};
}
button:hover, button.flat:hover { border-color: {{ accent }}; }
button:checked, button:active, button:checked:backdrop {
  background-color: {{ accent }};
  color: {{ background }};
}
button:disabled { color: {{ color8 }}; }

/* ── entries ────────────────────────────────────────────────────────────── */
entry, spinbutton, searchentry {
  background-color: {{ background }};
  color: {{ foreground }};
  border-color: {{ color8 }};
}
entry:focus, entry:focus-within { border-color: {{ accent }}; }
entry:disabled { color: {{ color8 }}; }
entry selection, entry:selected { background-color: {{ accent }}; color: {{ background }}; }
entry placeholder { color: {{ color8 }}; }

/* ── menus, popovers, tooltips ──────────────────────────────────────────── */
menu, .menu, popover, popover.background, .popover {
  background-color: {{ color0 }};
  color: {{ foreground }};
  border-color: {{ color8 }};
}
menuitem, .menuitem { color: {{ foreground }}; }
menuitem:hover, .menuitem:hover { background-color: {{ accent }}; color: {{ background }}; }
menuitem:disabled { color: {{ color8 }}; }
tooltip, tooltip.background {
  background-color: {{ color0 }};
  color: {{ foreground }};
  border-color: {{ color8 }};
}
tooltip decoration { background-color: {{ color0 }}; }

/* ── toolbar, separators, scrollbars ────────────────────────────────────── */
toolbar, .toolbar { background-color: {{ background }}; color: {{ foreground }}; }
separator { background-color: {{ color8 }}; }
scrollbar { background-color: {{ background }}; }
scrollbar slider { background-color: {{ color8 }}; }
scrollbar slider:hover { background-color: {{ accent }}; }
scrollbar slider:active { background-color: {{ accent }}; }

/* ── links and progress ─────────────────────────────────────────────────── */
link, *:link { color: {{ accent }}; }
progressbar progress { background-color: {{ accent }}; }
levelbar block.filled { background-color: {{ accent }}; }
